#include "stdio.h"
// generates "regdef.inc"

const char* NoteNames[17] =
{
    "Cn","Cs","Df","Dn","Ds","Ef","En","Fn","Fs","Gf","Gn","Gs","Af","An","As","Bf","Bn",
};
const int NoteValues[17] =
{
	0,1,1,2,3,3,4,5,6,6,7,8,8,9,10,10,11
};

int hard_divide()
{
	printf(";======================================="
	        "=======================================\n");	
}
int soft_divide()
{
	printf(";---------------------------------------"
	        "---------------------------------------\n");	
}
int comment(char* s)
{
	printf("; %s\n",s);
}

int main()
{
	int note,oct;
	long i;
	hard_divide();
	comment("");
	comment("Predefined constants for QCK (note names, registers, etc)");
	comment("");
	comment("This file is autogenerated; please do not modify it directly.");
	comment("");
	hard_divide();
	
	
	for(i=0x80000;i<0x80200;i++)
	{
		printf(".define r%02x%s %d\n",i&0xff,i&0x100 ? "i" : "",i);
	}
	
	for(i=0;i<8*17;i++)
	{
		oct = i/17;
		note = i%17;
		printf(".define %s%d %d\n",NoteNames[note],oct,3+(oct*12)+NoteValues[note]);
	}
	
	printf(".define Q__ 127\n");
	printf(".define CCC 255\n");
	printf(".define ___ 65536\n");
	
}
