;==============================================================================
;
;  Wave definitions; this file will soon be autogenerated.
;
;==============================================================================

	.export tab_wave
	
	.segment "BANK0"
	
tab_wave:
	.addr		wave_0
	.addr		wave_1

wave_0:
	.word	$1200
	.word	$0000, $0006, $0000, $7ffd, $0000  
wave_1:
	.word	$1200
	.word	$0000, $0006, $9000, $fffd, $8000  

	